language: c

script:
- echo 'test'

cache: ccache

jobs:
  include:
  - os: osx
    before_install:
      - sw_vers
    osx_image: xcode6.4
    name: '10.10'
    cache: *osx_cache
  - os: osx
    before_install:
      - sw_vers
    osx_image: xcode7.3 # macOS 10.11
    name: '10.11'
    cache: *osx_cache
  - os: osx
    before_install:
      - sw_vers
    osx_image: xcode8.3 # macOS 10.12
    name: '10.12'
    cache: *osx_cache
  - os: osx
    before_install:
      - sw_vers
    osx_image: xcode9.4 # macOS 10.13
    name: '10.13'
    cache: *osx_cache
  - os: osx
    before_install:
      - sw_vers
    osx_image: xcode10.2 # macOS 10.14
    name: '10.14'
    cache: *osx_cache

before_cache:
  - echo rvm_auto_reload_flag=1 >> ~/.rvmrc

notifications:
  email: false
